version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=rpo-app
      - DB_USER=root
      - DB_PASS=root

  database:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rpo-app
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: