CREATE DATABASE IF NOT EXISTS `rpo-app`;
USE `rpo-app`;

CREATE TABLE company (
   id INT AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(256) NOT NULL,
   ico VARCHAR(32) NOT NULL UNIQUE,
   formatedAddress VARCHAR(256),
   street VARCHAR(256),
   building_number VARCHAR(16),
   postal_code VARCHAR(16),
   city VARCHAR(256),
   country VARCHAR(256),
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE advertisement (
  id INT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  text VARCHAR(2048) NOT NULL,
  logo_url VARCHAR(512),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (company_id) REFERENCES company(id) ON DELETE CASCADE
);